CREATE TABLE T_USUARIO 
	(
	ID_USUARIO INTEGER NOT NULL,
	NM_USUARIO VARCHAR2 (100) NOT NULL,
	DS_EMAIL VARCHAR2 (100) NOT NULL,
	DT_NASCIMENTO DATE NOT NULL,
	SENHA VARCHAR2 (50) NOT NULL,
	NMR_CELULAR INTEGER NOT NULL,
	);


ALTER TABLE T_USUARIO
	ADD CONSTRAINT ID_USUARIO_PK PRIMARY KEY (ID_USUARIO);




CREATE TABLE T_RECEITA
	(
	ID_RECEITA INTEGER NOT NULL,
	DS_RECEITA VARCHAR2 (100) NOT NULL,
	VLR_RECEITTA NUMBER (9,2) NOT NULL,
	DT_RECEITA DATE NOT NULL,
	TP_RECEITA VARCHAR2 (100) NOT NULL,
	VLR_TOTAL_RECEITA NUMBER (9,2) NOT NULL,
	ID_USUARIO INTEGER
	);

ALTER TABLE T_RECEITA
	ADD CONSTRAINT T_RECEITA_PK PRIMARY KEY (ID_RECEITA);

ALTER TABLE T_RECEITA
	ADD CONSTRAINT T_RECEITA_T_USUARIO_FK FOREIGN KEY (ID_USUARIO) REFERENCES T_USUARIO (ID_USUARIO);


CREATE TABLE T_DESPESA
(
ID_DESPESA INTEGER NOT NULL,
DS_DESPESA VARCHAR2 (100) NOT NULL,
VLR_DESPESA NUMBER (9,2) NOT NULL,
DT_DESPESA DATE NOT NULL,
TP_DESPESA VARCHAR2 (100),
VLR_TOTAL_DESPESA NUMBER (9,2),
ID_USUARIO INTEGER
);


ALTER TABLE T_DESPESA
	ADD CONSTRAINT T_DESPESA_PK PRIMARY KEY (ID_DESPESA);

ALTER TABLE T_DESPESA
	ADD CONSTRAINT T_DESPESA_T_USUARIO_FK FOREIGN KEY (ID_USUARIO) REFERENCES T_USUARIO (ID_USUARIO);


CREATE TABLE T_INVESTIMENTO
	(
	ID_INVESTIMENTO INTEGER NOT NULL,
	DS_INVESTIMENTO VARCHAR2 (100) NOT NULL,
	VLR_INVESTIMENTO NUMBER(9,2) NOT NULL,
	DT_INVESTIMENTO DATE NOT NULL,
	DT_VENCIMENTO DATE NOT NULL,
	DT_RESGATE DATE NOT NULL,
	ID_USUARIO INTEGER
	);


ALTER TABLE T_INVESTIMENTO
	ADD CONSTRAINT T_INVESTIMENTO_PK PRIMARY KEY (ID_INVESTIMENTO);

ALTER TABLE T_INVESTIMENTO
	ADD CONSTRAINT T_INVESTIMENTO_T_USUARIO_FK FOREIGN KEY (ID_USUARIO) REFERENCES T_USUARIO (ID_USUARIO);




CREATE TABLE T_LEMBRETE
	(
	ID_LEMBRETE INTEGER NOT NULL,
	DT_LEMBRETE DATE NOT NULL,
	HR_LEMBRETE TIMESTAMP NOT NULL,
	DS_LEMBRETE VARCHAR2 (100) NOT NULL,
	ID_USUARIO INTEGER
	);


ALTER TABLE T_LEMBRETE
	ADD CONSTRAINT T_LEMBRETE_PK PRIMARY KEY (ID_LEMBRETE);

ALTER TABLE T_LEMBRETE
	ADD CONSTRAINT T_LEMBRETE_T_USUARIO_FK FOREIGN KEY (ID_USUARIO) REFERENCES T_USUARIO (ID_USUARIO);


CREATE TABLE T_BALANCO
	(
	ID_BALANCO INTEGER NOT NULL,
	DT_INICIAL DATE NOT NULL,
	DT_FINAL DATE NOT NULL,
	DT_BALANCO DATE NOT NULL,
	VLR_BALANCO NUMBER (9,2) NOT NULL,
	ID_USUARIO INTEGER
	);


ALTER TABLE T_BALANCO
	ADD CONSTRAINT T_BALANCO_T_RECEITA_FK FOREIGN KEY (ID_RECEITA) REFERENCES T_RECEITA (ID_RECEITA);

ALTER TABLE T_BALANCO
	ADD CONSTRAINT T_BALANCO_T_DESPESA_FK FOREIGN KEY (ID_DESPESA) REFERENCES T_DESPESA (ID_DESPESA);


CREATE TABLE T_CONTA
	(
	ID_CONTA INTEGER NOT NULL,
	ID_USUARIO INTEGER,
    LOGIN VARCHAR2 (60) NOT NULL,
	SENHA VARCHAR2(60) NOT NULL,
    NM_USUARIO VARCHAR2(60) NULL,
    DT_ALTERACAO_SENHA DATE  NOT NULL
	);

ALTER TABLE T_CONTA
	ADD CONSTRAINT ID_CONTA_PK PRIMARY KEY (ID_CONTA);
